@echo off
chcp 65001 >nul

python scripts/word_cloud.py --radical 1 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_一_all.txt
python scripts/word_cloud.py --radical 2 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_丨_all.txt
python scripts/word_cloud.py --radical 3 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_丶_all.txt
python scripts/word_cloud.py --radical 4 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_丿_all.txt
python scripts/word_cloud.py --radical 5 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_乙_all.txt
python scripts/word_cloud.py --radical 6 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_亅_all.txt
python scripts/word_cloud.py --radical 7 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_二_all.txt
python scripts/word_cloud.py --radical 8 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_亠_all.txt
python scripts/word_cloud.py --radical 9 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_人_all.txt
python scripts/word_cloud.py --radical 10 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_儿_all.txt
python scripts/word_cloud.py --radical 11 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_入_all.txt
python scripts/word_cloud.py --radical 12 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_八_all.txt
python scripts/word_cloud.py --radical 13 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_冂_all.txt
python scripts/word_cloud.py --radical 14 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_冖_all.txt
python scripts/word_cloud.py --radical 15 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_冫_all.txt
python scripts/word_cloud.py --radical 16 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_几_all.txt
python scripts/word_cloud.py --radical 17 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_凵_all.txt
python scripts/word_cloud.py --radical 18 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_刀_all.txt
python scripts/word_cloud.py --radical 19 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_力_all.txt
python scripts/word_cloud.py --radical 20 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_勹_all.txt
python scripts/word_cloud.py --radical 21 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_匕_all.txt
python scripts/word_cloud.py --radical 22 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_匚_all.txt
python scripts/word_cloud.py --radical 23 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_匸_all.txt
python scripts/word_cloud.py --radical 24 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_十_all.txt
python scripts/word_cloud.py --radical 25 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_卜_all.txt
python scripts/word_cloud.py --radical 26 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_卩_all.txt
python scripts/word_cloud.py --radical 27 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_厂_all.txt
python scripts/word_cloud.py --radical 28 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_厶_all.txt
python scripts/word_cloud.py --radical 29 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_又_all.txt
python scripts/word_cloud.py --radical 30 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_口_all.txt
python scripts/word_cloud.py --radical 31 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_囗_all.txt
python scripts/word_cloud.py --radical 32 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_土_all.txt
python scripts/word_cloud.py --radical 33 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_士_all.txt
python scripts/word_cloud.py --radical 34 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_夂_all.txt
python scripts/word_cloud.py --radical 35 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_夊_all.txt
python scripts/word_cloud.py --radical 36 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_夕_all.txt
python scripts/word_cloud.py --radical 37 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_大_all.txt
python scripts/word_cloud.py --radical 38 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_女_all.txt
python scripts/word_cloud.py --radical 39 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_子_all.txt
python scripts/word_cloud.py --radical 40 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_宀_all.txt
python scripts/word_cloud.py --radical 41 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_寸_all.txt
python scripts/word_cloud.py --radical 42 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_小_all.txt
python scripts/word_cloud.py --radical 43 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_尢_all.txt
python scripts/word_cloud.py --radical 44 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_尸_all.txt
python scripts/word_cloud.py --radical 45 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_屮_all.txt
python scripts/word_cloud.py --radical 46 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_山_all.txt
python scripts/word_cloud.py --radical 47 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_巛_all.txt
python scripts/word_cloud.py --radical 48 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_工_all.txt
python scripts/word_cloud.py --radical 49 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_己_all.txt
python scripts/word_cloud.py --radical 50 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_巾_all.txt
python scripts/word_cloud.py --radical 51 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_干_all.txt
python scripts/word_cloud.py --radical 52 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_幺_all.txt
python scripts/word_cloud.py --radical 53 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_广_all.txt
python scripts/word_cloud.py --radical 54 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_廴_all.txt
python scripts/word_cloud.py --radical 55 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_廾_all.txt
python scripts/word_cloud.py --radical 56 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_弋_all.txt
python scripts/word_cloud.py --radical 57 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_弓_all.txt
python scripts/word_cloud.py --radical 58 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_彐_all.txt
python scripts/word_cloud.py --radical 59 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_彡_all.txt
python scripts/word_cloud.py --radical 60 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_彳_all.txt
python scripts/word_cloud.py --radical 61 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_心_all.txt
python scripts/word_cloud.py --radical 62 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_戈_all.txt
python scripts/word_cloud.py --radical 63 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_戶_all.txt
python scripts/word_cloud.py --radical 64 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_手_all.txt
python scripts/word_cloud.py --radical 65 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_支_all.txt
python scripts/word_cloud.py --radical 66 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_攴_all.txt
python scripts/word_cloud.py --radical 67 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_文_all.txt
python scripts/word_cloud.py --radical 68 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_斗_all.txt
python scripts/word_cloud.py --radical 69 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_斤_all.txt
python scripts/word_cloud.py --radical 70 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_方_all.txt
python scripts/word_cloud.py --radical 71 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_无_all.txt
python scripts/word_cloud.py --radical 72 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_日_all.txt
python scripts/word_cloud.py --radical 73 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_曰_all.txt
python scripts/word_cloud.py --radical 74 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_月_all.txt
python scripts/word_cloud.py --radical 75 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_木_all.txt
python scripts/word_cloud.py --radical 76 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_欠_all.txt
python scripts/word_cloud.py --radical 77 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_止_all.txt
python scripts/word_cloud.py --radical 78 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_歹_all.txt
python scripts/word_cloud.py --radical 79 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_殳_all.txt
python scripts/word_cloud.py --radical 80 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_毋_all.txt
python scripts/word_cloud.py --radical 81 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_比_all.txt
python scripts/word_cloud.py --radical 82 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_毛_all.txt
python scripts/word_cloud.py --radical 83 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_氏_all.txt
python scripts/word_cloud.py --radical 84 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_气_all.txt
python scripts/word_cloud.py --radical 85 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_水_all.txt
python scripts/word_cloud.py --radical 86 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_火_all.txt
python scripts/word_cloud.py --radical 87 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_爪_all.txt
python scripts/word_cloud.py --radical 88 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_父_all.txt
python scripts/word_cloud.py --radical 89 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_爻_all.txt
python scripts/word_cloud.py --radical 90 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_爿_all.txt
python scripts/word_cloud.py --radical 91 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_片_all.txt
python scripts/word_cloud.py --radical 92 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_牙_all.txt
python scripts/word_cloud.py --radical 93 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_牛_all.txt
python scripts/word_cloud.py --radical 94 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_犬_all.txt
python scripts/word_cloud.py --radical 95 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_玄_all.txt
python scripts/word_cloud.py --radical 96 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_玉_all.txt
python scripts/word_cloud.py --radical 97 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_瓜_all.txt
python scripts/word_cloud.py --radical 98 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_瓦_all.txt
python scripts/word_cloud.py --radical 99 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_甘_all.txt
python scripts/word_cloud.py --radical 100 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_生_all.txt
python scripts/word_cloud.py --radical 101 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_用_all.txt
python scripts/word_cloud.py --radical 102 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_田_all.txt
python scripts/word_cloud.py --radical 103 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_疋_all.txt
python scripts/word_cloud.py --radical 104 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_疒_all.txt
python scripts/word_cloud.py --radical 105 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_癶_all.txt
python scripts/word_cloud.py --radical 106 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_白_all.txt
python scripts/word_cloud.py --radical 107 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_皮_all.txt
python scripts/word_cloud.py --radical 108 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_皿_all.txt
python scripts/word_cloud.py --radical 109 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_目_all.txt
python scripts/word_cloud.py --radical 110 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_矛_all.txt
python scripts/word_cloud.py --radical 111 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_矢_all.txt
python scripts/word_cloud.py --radical 112 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_石_all.txt
python scripts/word_cloud.py --radical 113 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_示_all.txt
python scripts/word_cloud.py --radical 114 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_禸_all.txt
python scripts/word_cloud.py --radical 115 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_禾_all.txt
python scripts/word_cloud.py --radical 116 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_穴_all.txt
python scripts/word_cloud.py --radical 117 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_立_all.txt
python scripts/word_cloud.py --radical 118 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_竹_all.txt
python scripts/word_cloud.py --radical 119 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_米_all.txt
python scripts/word_cloud.py --radical 120 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_糸_all.txt
python scripts/word_cloud.py --radical 121 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_缶_all.txt
python scripts/word_cloud.py --radical 122 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_网_all.txt
python scripts/word_cloud.py --radical 123 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_羊_all.txt
python scripts/word_cloud.py --radical 124 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_羽_all.txt
python scripts/word_cloud.py --radical 125 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_老_all.txt
python scripts/word_cloud.py --radical 126 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_而_all.txt
python scripts/word_cloud.py --radical 127 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_耒_all.txt
python scripts/word_cloud.py --radical 128 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_耳_all.txt
python scripts/word_cloud.py --radical 129 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_聿_all.txt
python scripts/word_cloud.py --radical 130 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_肉_all.txt
python scripts/word_cloud.py --radical 131 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_臣_all.txt
python scripts/word_cloud.py --radical 132 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_自_all.txt
python scripts/word_cloud.py --radical 133 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_至_all.txt
python scripts/word_cloud.py --radical 134 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_臼_all.txt
python scripts/word_cloud.py --radical 135 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_舌_all.txt
python scripts/word_cloud.py --radical 136 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_舛_all.txt
python scripts/word_cloud.py --radical 137 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_舟_all.txt
python scripts/word_cloud.py --radical 138 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_艮_all.txt
python scripts/word_cloud.py --radical 139 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_色_all.txt
python scripts/word_cloud.py --radical 140 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_艸_all.txt
python scripts/word_cloud.py --radical 141 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_虍_all.txt
python scripts/word_cloud.py --radical 142 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_虫_all.txt
python scripts/word_cloud.py --radical 143 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_血_all.txt
python scripts/word_cloud.py --radical 144 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_行_all.txt
python scripts/word_cloud.py --radical 145 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_衣_all.txt
python scripts/word_cloud.py --radical 146 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_襾_all.txt
python scripts/word_cloud.py --radical 147 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_見_all.txt
python scripts/word_cloud.py --radical 148 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_角_all.txt
python scripts/word_cloud.py --radical 149 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_言_all.txt
python scripts/word_cloud.py --radical 150 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_谷_all.txt
python scripts/word_cloud.py --radical 151 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_豆_all.txt
python scripts/word_cloud.py --radical 152 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_豕_all.txt
python scripts/word_cloud.py --radical 153 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_豸_all.txt
python scripts/word_cloud.py --radical 154 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_貝_all.txt
python scripts/word_cloud.py --radical 155 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_赤_all.txt
python scripts/word_cloud.py --radical 156 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_走_all.txt
python scripts/word_cloud.py --radical 157 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_足_all.txt
python scripts/word_cloud.py --radical 158 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_身_all.txt
python scripts/word_cloud.py --radical 159 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_車_all.txt
python scripts/word_cloud.py --radical 160 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_辛_all.txt
python scripts/word_cloud.py --radical 161 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_辰_all.txt
python scripts/word_cloud.py --radical 162 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_辵_all.txt
python scripts/word_cloud.py --radical 163 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_邑_all.txt
python scripts/word_cloud.py --radical 164 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_酉_all.txt
python scripts/word_cloud.py --radical 165 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_釆_all.txt
python scripts/word_cloud.py --radical 166 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_里_all.txt
python scripts/word_cloud.py --radical 167 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_金_all.txt
python scripts/word_cloud.py --radical 168 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_長_all.txt
python scripts/word_cloud.py --radical 169 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_門_all.txt
python scripts/word_cloud.py --radical 170 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_阜_all.txt
python scripts/word_cloud.py --radical 171 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_隶_all.txt
python scripts/word_cloud.py --radical 172 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_隹_all.txt
python scripts/word_cloud.py --radical 173 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_雨_all.txt
python scripts/word_cloud.py --radical 174 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_靑_all.txt
python scripts/word_cloud.py --radical 175 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_非_all.txt
python scripts/word_cloud.py --radical 176 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_面_all.txt
python scripts/word_cloud.py --radical 177 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_革_all.txt
python scripts/word_cloud.py --radical 178 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_韋_all.txt
python scripts/word_cloud.py --radical 179 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_韭_all.txt
python scripts/word_cloud.py --radical 180 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_音_all.txt
python scripts/word_cloud.py --radical 181 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_頁_all.txt
python scripts/word_cloud.py --radical 182 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_風_all.txt
python scripts/word_cloud.py --radical 183 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_飛_all.txt
python scripts/word_cloud.py --radical 184 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_食_all.txt
python scripts/word_cloud.py --radical 185 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_首_all.txt
python scripts/word_cloud.py --radical 186 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_香_all.txt
python scripts/word_cloud.py --radical 187 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_馬_all.txt
python scripts/word_cloud.py --radical 188 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_骨_all.txt
python scripts/word_cloud.py --radical 189 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_高_all.txt
python scripts/word_cloud.py --radical 190 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_髟_all.txt
python scripts/word_cloud.py --radical 191 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鬥_all.txt
python scripts/word_cloud.py --radical 192 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鬯_all.txt
python scripts/word_cloud.py --radical 193 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鬲_all.txt
python scripts/word_cloud.py --radical 194 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鬼_all.txt
python scripts/word_cloud.py --radical 195 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_魚_all.txt
python scripts/word_cloud.py --radical 196 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鳥_all.txt
python scripts/word_cloud.py --radical 197 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鹵_all.txt
python scripts/word_cloud.py --radical 198 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鹿_all.txt
python scripts/word_cloud.py --radical 199 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_麥_all.txt
python scripts/word_cloud.py --radical 200 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_麻_all.txt
python scripts/word_cloud.py --radical 201 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_黃_all.txt
python scripts/word_cloud.py --radical 202 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_黍_all.txt
python scripts/word_cloud.py --radical 203 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_黑_all.txt
python scripts/word_cloud.py --radical 204 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_黹_all.txt
python scripts/word_cloud.py --radical 205 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_黽_all.txt
python scripts/word_cloud.py --radical 206 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鼎_all.txt
python scripts/word_cloud.py --radical 207 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鼓_all.txt
python scripts/word_cloud.py --radical 208 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鼠_all.txt
python scripts/word_cloud.py --radical 209 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_鼻_all.txt
python scripts/word_cloud.py --radical 210 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_齊_all.txt
python scripts/word_cloud.py --radical 211 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_齒_all.txt
python scripts/word_cloud.py --radical 212 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_龍_all.txt
python scripts/word_cloud.py --radical 213 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_龜_all.txt
python scripts/word_cloud.py --radical 214 --top all --image-out-dir word_clouds --include-sources >word_clouds/radical_龠_all.txt
